defaults: &defaults
  help_url: "http://www.railstutorial.org/help"
  book_url: "http://www.railstutorial.org/book"
  tutorial_url: "http://www.railstutorial.org/"
  avatar_change_url: "http://gravatar.com/emails"
  host: "localhost:3000"

expire_time: 2
resize_to_limit:
  - 500
  - 500
max_size: 5

users:
  email_validate_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
  name_max_length: 50
  email_max_length: 255
  password_min_length: 6
  gravatar:
    heading: "https://secure.gravatar.com/avatar/"
    default_size: 80
    display_size: 50
    follow_size: 30
  page: 10

microposts:
  content_max_size: 140
  allowed_image_mime_types:
    - image/jpeg
    - image/gif
    - image/png
  accept_image: "image/jpeg,image/gif,image/png"

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
